HackInTheNorth/hackinthenorth.github.io

register.html
this page is basic layout without the styling and color combination and background
=> Registration page basic layout

css/stylesheet.css
Reverts pradyumna1/hackInNorth-website#4
added responsiveness is good but the navigation dots were looking better previously
=> Revert "navigation bar adjustable "

index.html
Final ROund Demos fixed to Final Round Demos
=> Fixed typo in Schedule

css/stylesheet.css, index.html
=> Improved the font and color

team page/team.html
Finished the remaining missing details of organizers.
=> Completed team.html

projects/projects.js
=> no_ones entry

index.html, static/css/main.css, static/js/index.js
=> Added sticky navbar

index.html, static/css/main.css, static/js/countdown.js
@hackerkid @pradyumna1 
Resolves #69 and #70.
Many responsivity issues still remain.
=> add countdown timer and fixed few of the responsivity issues

index.html
I've updated the about section contents. Not so sure about the class names.
=> Update about section content

team.html
Added my github profile link please review.
=> Added my github profile

index.html
1. Remove Sponsor Us 
2. Add Chat with us : zulipchat
=> Add Chat with Us .

index.html, static/css/main.css
=> Change Radix as domain sponsor and remove Hackerearth

static/css/style.css
Subscribe for updates button CSS changed. Default visited color of anchor tag changed to white.
=> Subscribe button visited css

main/index.html
live link: http://anupamdagar.me/hack-in-the-north-preview-repo/main/
=> added animation in about and faq section [WIP]

main/index.html, main/static/css/main.css
live link http://anupamdagar.me/hack-in-the-north-preview-repo/main
please review.
=> changed font to vollkorn in whole website

main/index.html, main/static/css/cards.css, main/static/css/main.css
live link:
http://anupamdagar.me/hack-in-the-north-preview-repo/main/
=> Fullpage landing section

main/index.html, main/static/css/cards.css
Please take a look at the schedule, by default color almost matches with the site, if it is not fine then I will change.Responsive check is done for the schedule.
live link:
http://anupamdagar.me/hack-in-the-north-preview-repo/main/
=> fixed about section responsive issue and added schedule

main/index.html, main/static/css/cards.css, main/static/css/main.css, main/static/js/main.js, main/static/js/smooth-scroll.js
made sections full page, changed footer configuration, fixed contact small screen responsiveness, added map location, changed button colors
live link:
http://anupamdagar.me/hack-in-the-north-preview-repo/main/
=> Major changes

main/index.html, main/static/css/cards.css, main/static/js/faq.js, main/static/js/main.js
live link: 
http://anupamdagar.me/hack-in-the-north-preview-repo/main
=> finally faq jerk is fixed now, new code for js written.

main/index.html, main/static/css/cards.css
Removed unwanted changes. and added coc
=> Code of conduct

main/index.html, main/static/css/cards.css
Changes made 
1. Navbar:
1.1 Made Contact the last option
1.2 Added Schedule as an option since it is present on the page
2. Home section:
2.1 Change the dates to March 16-18, 2017 for now.
3. About:
3.1 Grammatical errors fixed.
3.5 Removed repeated text.
5. Map:
5.1 The transition to the map is very abrupt and the size of it should be reduced and an appropriate title like "Battleground" or something like that should be better.
5.2 Swapped Contact and Map.
6. Contact: Removed the hover transition.
=> minor changes

main/index.html, main/static/css/cards.css
live link:
http://anupamdagar.me/hack-in-the-north-preview-repo/
=> minor fixes

main/index.html
https://orionstar25.github.io/hackinthenorth.github.io/main/ - preview
=> faq questions added

main/index.html
https://orionstar25.github.io/hackinthenorth.github.io/main/ - preview
=> schedule added

main/index.html
https://orionstar25.github.io/hackinthenorth.github.io/main/
have fun
=>  lol change made

index.html
Live link : http://aswinzz.com/hackinthenorth.github.io/
=> Fix Responsiveness

static/css/cards.css
Live Link : http://aswinzz.com/hackinthenorth.github.io/
=> Fix about section

index.html
https://anupamdagar.me/hack-in-the-north-preview-repo/
=> fixed depth

static/css/cards.css
=> Fix fullpage class

index.html
http://aswinzz.com/hackinthenorth.github.io/ - Live Link
=> fix FAQ section overflow

index.html, static/css/main.css
Live Link : http://aswinzz.com/hackinthenorth.github.io/
=> add custom scrollbar

static/css/layout.css, team.html
[`Live link`](https://aswanthkoleri.github.io/hackinthenorth.github.io)
=> Add contact no

index.html
https://orionstar25.github.io/hackinthenorth.github.io/
=> change about content

index.html
https://orionstar25.github.io/hackinthenorth.github.io/
=> fix faq overflow

index.html, static/css/main.css
preview:
https://cosmiccoder96.github.io/hackinthenorth.github.io/index.html
=> Add gradient effect to navbar

index.html
- Twitter does not generate website preview.
- Also there is no specific meta data for Facebook preview but it uses information from other tags. If it is required we can add one.
=> Add meta data for webpage and remove unnecessary console logs

index.html, static/css/main.css
make background image of about and faq responsive
http://anupamdagar.me/hackinthenorth.github.io
=> add new sponsorship brochure, change flow from patron to media partner

index.html
Live link : https://aswanthkoleri.github.io/hackinthenorth.github.io/index.html
=> Add Infotech prize card 

index.html
=> Change description of Kloudless 

index.html
https://arpitmisraw.github.io/hackinthenorth.github.io/
=> Made the Sponsor's section responsive for mobile view

index.html
Fixes: #286 
https://anupam-dagar.github.io/hackinthenorth.github.io
=> applications are closed

index.html
=> Updated infotechub link in sponsors

index.html
https://anupam-dagar.github.io/hackinthenorth.github.io
=> fix last line of patron alignment
